// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Complex.proto

package com.whg.protobuf;

public final class ComplexProtoBuf {
  private ComplexProtoBuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface CarOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string model = 1;
    boolean hasModel();
    String getModel();
    
    // required .Game.Cars.Car.Vendor vendor = 2;
    boolean hasVendor();
    com.whg.protobuf.ComplexProtoBuf.Car.Vendor getVendor();
    com.whg.protobuf.ComplexProtoBuf.Car.VendorOrBuilder getVendorOrBuilder();
    
    // optional .Game.Cars.Car.Speed speed = 3 [default = FAST];
    boolean hasSpeed();
    com.whg.protobuf.ComplexProtoBuf.Car.Speed getSpeed();
  }
  public static final class Car extends
      com.google.protobuf.GeneratedMessage
      implements CarOrBuilder {
    // Use Car.newBuilder() to construct.
    private Car(Builder builder) {
      super(builder);
    }
    private Car(boolean noInit) {}
    
    private static final Car defaultInstance;
    public static Car getDefaultInstance() {
      return defaultInstance;
    }
    
    public Car getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.whg.protobuf.ComplexProtoBuf.internal_static_Game_Cars_Car_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.whg.protobuf.ComplexProtoBuf.internal_static_Game_Cars_Car_fieldAccessorTable;
    }
    
    public enum Speed
        implements com.google.protobuf.ProtocolMessageEnum {
      FAST(0, 1),
      SUPERFAST(1, 2),
      ;
      
      public static final int FAST_VALUE = 1;
      public static final int SUPERFAST_VALUE = 2;
      
      
      public final int getNumber() { return value; }
      
      public static Speed valueOf(int value) {
        switch (value) {
          case 1: return FAST;
          case 2: return SUPERFAST;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Speed>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Speed>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Speed>() {
              public Speed findValueByNumber(int number) {
                return Speed.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.whg.protobuf.ComplexProtoBuf.Car.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final Speed[] VALUES = {
        FAST, SUPERFAST, 
      };
      
      public static Speed valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private Speed(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:Game.Cars.Car.Speed)
    }
    
    public interface VendorOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
      
      // required string name = 1;
      boolean hasName();
      String getName();
      
      // optional .Game.Cars.Car.Vendor.Address address = 2;
      boolean hasAddress();
      com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address getAddress();
      com.whg.protobuf.ComplexProtoBuf.Car.Vendor.AddressOrBuilder getAddressOrBuilder();
    }
    public static final class Vendor extends
        com.google.protobuf.GeneratedMessage
        implements VendorOrBuilder {
      // Use Vendor.newBuilder() to construct.
      private Vendor(Builder builder) {
        super(builder);
      }
      private Vendor(boolean noInit) {}
      
      private static final Vendor defaultInstance;
      public static Vendor getDefaultInstance() {
        return defaultInstance;
      }
      
      public Vendor getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.whg.protobuf.ComplexProtoBuf.internal_static_Game_Cars_Car_Vendor_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.whg.protobuf.ComplexProtoBuf.internal_static_Game_Cars_Car_Vendor_fieldAccessorTable;
      }
      
      public interface AddressOrBuilder
          extends com.google.protobuf.MessageOrBuilder {
        
        // required string country = 1;
        boolean hasCountry();
        String getCountry();
      }
      public static final class Address extends
          com.google.protobuf.GeneratedMessage
          implements AddressOrBuilder {
        // Use Address.newBuilder() to construct.
        private Address(Builder builder) {
          super(builder);
        }
        private Address(boolean noInit) {}
        
        private static final Address defaultInstance;
        public static Address getDefaultInstance() {
          return defaultInstance;
        }
        
        public Address getDefaultInstanceForType() {
          return defaultInstance;
        }
        
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.whg.protobuf.ComplexProtoBuf.internal_static_Game_Cars_Car_Vendor_Address_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.whg.protobuf.ComplexProtoBuf.internal_static_Game_Cars_Car_Vendor_Address_fieldAccessorTable;
        }
        
        private int bitField0_;
        // required string country = 1;
        public static final int COUNTRY_FIELD_NUMBER = 1;
        private Object country_;
        public boolean hasCountry() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public String getCountry() {
          Object ref = country_;
          if (ref instanceof String) {
            return (String) ref;
          } else {
            com.google.protobuf.ByteString bs = 
                (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            if (com.google.protobuf.Internal.isValidUtf8(bs)) {
              country_ = s;
            }
            return s;
          }
        }
        private com.google.protobuf.ByteString getCountryBytes() {
          Object ref = country_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8((String) ref);
            country_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        
        private void initFields() {
          country_ = "";
        }
        private byte memoizedIsInitialized = -1;
        public final boolean isInitialized() {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized != -1) return isInitialized == 1;
          
          if (!hasCountry()) {
            memoizedIsInitialized = 0;
            return false;
          }
          memoizedIsInitialized = 1;
          return true;
        }
        
        public void writeTo(com.google.protobuf.CodedOutputStream output)
                            throws java.io.IOException {
          getSerializedSize();
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            output.writeBytes(1, getCountryBytes());
          }
          getUnknownFields().writeTo(output);
        }
        
        private int memoizedSerializedSize = -1;
        public int getSerializedSize() {
          int size = memoizedSerializedSize;
          if (size != -1) return size;
        
          size = 0;
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            size += com.google.protobuf.CodedOutputStream
              .computeBytesSize(1, getCountryBytes());
          }
          size += getUnknownFields().getSerializedSize();
          memoizedSerializedSize = size;
          return size;
        }
        
        @java.lang.Override
        protected Object writeReplace() throws java.io.ObjectStreamException {
          return super.writeReplace();
        }
        
        public static com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return newBuilder().mergeFrom(data).buildParsed();
        }
        public static com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return newBuilder().mergeFrom(data, extensionRegistry)
                   .buildParsed();
        }
        public static com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return newBuilder().mergeFrom(data).buildParsed();
        }
        public static com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return newBuilder().mergeFrom(data, extensionRegistry)
                   .buildParsed();
        }
        public static com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address parseFrom(java.io.InputStream input)
            throws java.io.IOException {
          return newBuilder().mergeFrom(input).buildParsed();
        }
        public static com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          return newBuilder().mergeFrom(input, extensionRegistry)
                   .buildParsed();
        }
        public static com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
          Builder builder = newBuilder();
          if (builder.mergeDelimitedFrom(input)) {
            return builder.buildParsed();
          } else {
            return null;
          }
        }
        public static com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          Builder builder = newBuilder();
          if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
            return builder.buildParsed();
          } else {
            return null;
          }
        }
        public static com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
          return newBuilder().mergeFrom(input).buildParsed();
        }
        public static com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          return newBuilder().mergeFrom(input, extensionRegistry)
                   .buildParsed();
        }
        
        public static Builder newBuilder() { return Builder.create(); }
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder(com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address prototype) {
          return newBuilder().mergeFrom(prototype);
        }
        public Builder toBuilder() { return newBuilder(this); }
        
        @java.lang.Override
        protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          Builder builder = new Builder(parent);
          return builder;
        }
        public static final class Builder extends
            com.google.protobuf.GeneratedMessage.Builder<Builder>
           implements com.whg.protobuf.ComplexProtoBuf.Car.Vendor.AddressOrBuilder {
          public static final com.google.protobuf.Descriptors.Descriptor
              getDescriptor() {
            return com.whg.protobuf.ComplexProtoBuf.internal_static_Game_Cars_Car_Vendor_Address_descriptor;
          }
          
          protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
              internalGetFieldAccessorTable() {
            return com.whg.protobuf.ComplexProtoBuf.internal_static_Game_Cars_Car_Vendor_Address_fieldAccessorTable;
          }
          
          // Construct using com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address.newBuilder()
          private Builder() {
            maybeForceBuilderInitialization();
          }
          
          private Builder(BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
          }
          private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
            }
          }
          private static Builder create() {
            return new Builder();
          }
          
          public Builder clear() {
            super.clear();
            country_ = "";
            bitField0_ = (bitField0_ & ~0x00000001);
            return this;
          }
          
          public Builder clone() {
            return create().mergeFrom(buildPartial());
          }
          
          public com.google.protobuf.Descriptors.Descriptor
              getDescriptorForType() {
            return com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address.getDescriptor();
          }
          
          public com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address getDefaultInstanceForType() {
            return com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address.getDefaultInstance();
          }
          
          public com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address build() {
            com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address result = buildPartial();
            if (!result.isInitialized()) {
              throw newUninitializedMessageException(result);
            }
            return result;
          }
          
          private com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address buildParsed()
              throws com.google.protobuf.InvalidProtocolBufferException {
            com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address result = buildPartial();
            if (!result.isInitialized()) {
              throw newUninitializedMessageException(
                result).asInvalidProtocolBufferException();
            }
            return result;
          }
          
          public com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address buildPartial() {
            com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address result = new com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address(this);
            int from_bitField0_ = bitField0_;
            int to_bitField0_ = 0;
            if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
              to_bitField0_ |= 0x00000001;
            }
            result.country_ = country_;
            result.bitField0_ = to_bitField0_;
            onBuilt();
            return result;
          }
          
          public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address) {
              return mergeFrom((com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address)other);
            } else {
              super.mergeFrom(other);
              return this;
            }
          }
          
          public Builder mergeFrom(com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address other) {
            if (other == com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address.getDefaultInstance()) return this;
            if (other.hasCountry()) {
              setCountry(other.getCountry());
            }
            this.mergeUnknownFields(other.getUnknownFields());
            return this;
          }
          
          public final boolean isInitialized() {
            if (!hasCountry()) {
              
              return false;
            }
            return true;
          }
          
          public Builder mergeFrom(
              com.google.protobuf.CodedInputStream input,
              com.google.protobuf.ExtensionRegistryLite extensionRegistry)
              throws java.io.IOException {
            com.google.protobuf.UnknownFieldSet.Builder unknownFields =
              com.google.protobuf.UnknownFieldSet.newBuilder(
                this.getUnknownFields());
            while (true) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                default: {
                  if (!parseUnknownField(input, unknownFields,
                                         extensionRegistry, tag)) {
                    this.setUnknownFields(unknownFields.build());
                    onChanged();
                    return this;
                  }
                  break;
                }
                case 10: {
                  bitField0_ |= 0x00000001;
                  country_ = input.readBytes();
                  break;
                }
              }
            }
          }
          
          private int bitField0_;
          
          // required string country = 1;
          private Object country_ = "";
          public boolean hasCountry() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
          }
          public String getCountry() {
            Object ref = country_;
            if (!(ref instanceof String)) {
              String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
              country_ = s;
              return s;
            } else {
              return (String) ref;
            }
          }
          public Builder setCountry(String value) {
            if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
            country_ = value;
            onChanged();
            return this;
          }
          public Builder clearCountry() {
            bitField0_ = (bitField0_ & ~0x00000001);
            country_ = getDefaultInstance().getCountry();
            onChanged();
            return this;
          }
          void setCountry(com.google.protobuf.ByteString value) {
            bitField0_ |= 0x00000001;
            country_ = value;
            onChanged();
          }
          
          // @@protoc_insertion_point(builder_scope:Game.Cars.Car.Vendor.Address)
        }
        
        static {
          defaultInstance = new Address(true);
          defaultInstance.initFields();
        }
        
        // @@protoc_insertion_point(class_scope:Game.Cars.Car.Vendor.Address)
      }
      
      private int bitField0_;
      // required string name = 1;
      public static final int NAME_FIELD_NUMBER = 1;
      private Object name_;
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getName() {
        Object ref = name_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (com.google.protobuf.Internal.isValidUtf8(bs)) {
            name_ = s;
          }
          return s;
        }
      }
      private com.google.protobuf.ByteString getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      
      // optional .Game.Cars.Car.Vendor.Address address = 2;
      public static final int ADDRESS_FIELD_NUMBER = 2;
      private com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address address_;
      public boolean hasAddress() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address getAddress() {
        return address_;
      }
      public com.whg.protobuf.ComplexProtoBuf.Car.Vendor.AddressOrBuilder getAddressOrBuilder() {
        return address_;
      }
      
      private void initFields() {
        name_ = "";
        address_ = com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address.getDefaultInstance();
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        if (!hasName()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (hasAddress()) {
          if (!getAddress().isInitialized()) {
            memoizedIsInitialized = 0;
            return false;
          }
        }
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getNameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeMessage(2, address_);
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getNameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, address_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      @java.lang.Override
      protected Object writeReplace() throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static com.whg.protobuf.ComplexProtoBuf.Car.Vendor parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.whg.protobuf.ComplexProtoBuf.Car.Vendor parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.whg.protobuf.ComplexProtoBuf.Car.Vendor parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.whg.protobuf.ComplexProtoBuf.Car.Vendor parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.whg.protobuf.ComplexProtoBuf.Car.Vendor parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.whg.protobuf.ComplexProtoBuf.Car.Vendor parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static com.whg.protobuf.ComplexProtoBuf.Car.Vendor parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static com.whg.protobuf.ComplexProtoBuf.Car.Vendor parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static com.whg.protobuf.ComplexProtoBuf.Car.Vendor parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.whg.protobuf.ComplexProtoBuf.Car.Vendor parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.whg.protobuf.ComplexProtoBuf.Car.Vendor prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.whg.protobuf.ComplexProtoBuf.Car.VendorOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.whg.protobuf.ComplexProtoBuf.internal_static_Game_Cars_Car_Vendor_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.whg.protobuf.ComplexProtoBuf.internal_static_Game_Cars_Car_Vendor_fieldAccessorTable;
        }
        
        // Construct using com.whg.protobuf.ComplexProtoBuf.Car.Vendor.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private Builder(BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
            getAddressFieldBuilder();
          }
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          name_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          if (addressBuilder_ == null) {
            address_ = com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address.getDefaultInstance();
          } else {
            addressBuilder_.clear();
          }
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.whg.protobuf.ComplexProtoBuf.Car.Vendor.getDescriptor();
        }
        
        public com.whg.protobuf.ComplexProtoBuf.Car.Vendor getDefaultInstanceForType() {
          return com.whg.protobuf.ComplexProtoBuf.Car.Vendor.getDefaultInstance();
        }
        
        public com.whg.protobuf.ComplexProtoBuf.Car.Vendor build() {
          com.whg.protobuf.ComplexProtoBuf.Car.Vendor result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private com.whg.protobuf.ComplexProtoBuf.Car.Vendor buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          com.whg.protobuf.ComplexProtoBuf.Car.Vendor result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public com.whg.protobuf.ComplexProtoBuf.Car.Vendor buildPartial() {
          com.whg.protobuf.ComplexProtoBuf.Car.Vendor result = new com.whg.protobuf.ComplexProtoBuf.Car.Vendor(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.name_ = name_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          if (addressBuilder_ == null) {
            result.address_ = address_;
          } else {
            result.address_ = addressBuilder_.build();
          }
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.whg.protobuf.ComplexProtoBuf.Car.Vendor) {
            return mergeFrom((com.whg.protobuf.ComplexProtoBuf.Car.Vendor)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(com.whg.protobuf.ComplexProtoBuf.Car.Vendor other) {
          if (other == com.whg.protobuf.ComplexProtoBuf.Car.Vendor.getDefaultInstance()) return this;
          if (other.hasName()) {
            setName(other.getName());
          }
          if (other.hasAddress()) {
            mergeAddress(other.getAddress());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public final boolean isInitialized() {
          if (!hasName()) {
            
            return false;
          }
          if (hasAddress()) {
            if (!getAddress().isInitialized()) {
              
              return false;
            }
          }
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                name_ = input.readBytes();
                break;
              }
              case 18: {
                com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address.Builder subBuilder = com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address.newBuilder();
                if (hasAddress()) {
                  subBuilder.mergeFrom(getAddress());
                }
                input.readMessage(subBuilder, extensionRegistry);
                setAddress(subBuilder.buildPartial());
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // required string name = 1;
        private Object name_ = "";
        public boolean hasName() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public String getName() {
          Object ref = name_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
            name_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        public Builder setName(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          name_ = value;
          onChanged();
          return this;
        }
        public Builder clearName() {
          bitField0_ = (bitField0_ & ~0x00000001);
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        void setName(com.google.protobuf.ByteString value) {
          bitField0_ |= 0x00000001;
          name_ = value;
          onChanged();
        }
        
        // optional .Game.Cars.Car.Vendor.Address address = 2;
        private com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address address_ = com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address.getDefaultInstance();
        private com.google.protobuf.SingleFieldBuilder<
            com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address, com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address.Builder, com.whg.protobuf.ComplexProtoBuf.Car.Vendor.AddressOrBuilder> addressBuilder_;
        public boolean hasAddress() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        public com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address getAddress() {
          if (addressBuilder_ == null) {
            return address_;
          } else {
            return addressBuilder_.getMessage();
          }
        }
        public Builder setAddress(com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address value) {
          if (addressBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            address_ = value;
            onChanged();
          } else {
            addressBuilder_.setMessage(value);
          }
          bitField0_ |= 0x00000002;
          return this;
        }
        public Builder setAddress(
            com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address.Builder builderForValue) {
          if (addressBuilder_ == null) {
            address_ = builderForValue.build();
            onChanged();
          } else {
            addressBuilder_.setMessage(builderForValue.build());
          }
          bitField0_ |= 0x00000002;
          return this;
        }
        public Builder mergeAddress(com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address value) {
          if (addressBuilder_ == null) {
            if (((bitField0_ & 0x00000002) == 0x00000002) &&
                address_ != com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address.getDefaultInstance()) {
              address_ =
                com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address.newBuilder(address_).mergeFrom(value).buildPartial();
            } else {
              address_ = value;
            }
            onChanged();
          } else {
            addressBuilder_.mergeFrom(value);
          }
          bitField0_ |= 0x00000002;
          return this;
        }
        public Builder clearAddress() {
          if (addressBuilder_ == null) {
            address_ = com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address.getDefaultInstance();
            onChanged();
          } else {
            addressBuilder_.clear();
          }
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }
        public com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address.Builder getAddressBuilder() {
          bitField0_ |= 0x00000002;
          onChanged();
          return getAddressFieldBuilder().getBuilder();
        }
        public com.whg.protobuf.ComplexProtoBuf.Car.Vendor.AddressOrBuilder getAddressOrBuilder() {
          if (addressBuilder_ != null) {
            return addressBuilder_.getMessageOrBuilder();
          } else {
            return address_;
          }
        }
        private com.google.protobuf.SingleFieldBuilder<
            com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address, com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address.Builder, com.whg.protobuf.ComplexProtoBuf.Car.Vendor.AddressOrBuilder> 
            getAddressFieldBuilder() {
          if (addressBuilder_ == null) {
            addressBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address, com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address.Builder, com.whg.protobuf.ComplexProtoBuf.Car.Vendor.AddressOrBuilder>(
                    address_,
                    getParentForChildren(),
                    isClean());
            address_ = null;
          }
          return addressBuilder_;
        }
        
        // @@protoc_insertion_point(builder_scope:Game.Cars.Car.Vendor)
      }
      
      static {
        defaultInstance = new Vendor(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:Game.Cars.Car.Vendor)
    }
    
    public interface HolderOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
      
      // optional string first_name = 1;
      boolean hasFirstName();
      String getFirstName();
      
      // required string last_name = 2;
      boolean hasLastName();
      String getLastName();
      
      // optional .Game.Cars.Car.Vendor.Address address = 3;
      boolean hasAddress();
      com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address getAddress();
      com.whg.protobuf.ComplexProtoBuf.Car.Vendor.AddressOrBuilder getAddressOrBuilder();
    }
    public static final class Holder extends
        com.google.protobuf.GeneratedMessage
        implements HolderOrBuilder {
      // Use Holder.newBuilder() to construct.
      private Holder(Builder builder) {
        super(builder);
      }
      private Holder(boolean noInit) {}
      
      private static final Holder defaultInstance;
      public static Holder getDefaultInstance() {
        return defaultInstance;
      }
      
      public Holder getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.whg.protobuf.ComplexProtoBuf.internal_static_Game_Cars_Car_Holder_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.whg.protobuf.ComplexProtoBuf.internal_static_Game_Cars_Car_Holder_fieldAccessorTable;
      }
      
      private int bitField0_;
      // optional string first_name = 1;
      public static final int FIRST_NAME_FIELD_NUMBER = 1;
      private Object firstName_;
      public boolean hasFirstName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getFirstName() {
        Object ref = firstName_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (com.google.protobuf.Internal.isValidUtf8(bs)) {
            firstName_ = s;
          }
          return s;
        }
      }
      private com.google.protobuf.ByteString getFirstNameBytes() {
        Object ref = firstName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          firstName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      
      // required string last_name = 2;
      public static final int LAST_NAME_FIELD_NUMBER = 2;
      private Object lastName_;
      public boolean hasLastName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getLastName() {
        Object ref = lastName_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (com.google.protobuf.Internal.isValidUtf8(bs)) {
            lastName_ = s;
          }
          return s;
        }
      }
      private com.google.protobuf.ByteString getLastNameBytes() {
        Object ref = lastName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          lastName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      
      // optional .Game.Cars.Car.Vendor.Address address = 3;
      public static final int ADDRESS_FIELD_NUMBER = 3;
      private com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address address_;
      public boolean hasAddress() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address getAddress() {
        return address_;
      }
      public com.whg.protobuf.ComplexProtoBuf.Car.Vendor.AddressOrBuilder getAddressOrBuilder() {
        return address_;
      }
      
      private void initFields() {
        firstName_ = "";
        lastName_ = "";
        address_ = com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address.getDefaultInstance();
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        if (!hasLastName()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (hasAddress()) {
          if (!getAddress().isInitialized()) {
            memoizedIsInitialized = 0;
            return false;
          }
        }
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getFirstNameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getLastNameBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeMessage(3, address_);
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getFirstNameBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getLastNameBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(3, address_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      @java.lang.Override
      protected Object writeReplace() throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static com.whg.protobuf.ComplexProtoBuf.Car.Holder parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.whg.protobuf.ComplexProtoBuf.Car.Holder parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.whg.protobuf.ComplexProtoBuf.Car.Holder parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static com.whg.protobuf.ComplexProtoBuf.Car.Holder parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static com.whg.protobuf.ComplexProtoBuf.Car.Holder parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.whg.protobuf.ComplexProtoBuf.Car.Holder parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static com.whg.protobuf.ComplexProtoBuf.Car.Holder parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static com.whg.protobuf.ComplexProtoBuf.Car.Holder parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static com.whg.protobuf.ComplexProtoBuf.Car.Holder parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static com.whg.protobuf.ComplexProtoBuf.Car.Holder parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.whg.protobuf.ComplexProtoBuf.Car.Holder prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.whg.protobuf.ComplexProtoBuf.Car.HolderOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.whg.protobuf.ComplexProtoBuf.internal_static_Game_Cars_Car_Holder_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.whg.protobuf.ComplexProtoBuf.internal_static_Game_Cars_Car_Holder_fieldAccessorTable;
        }
        
        // Construct using com.whg.protobuf.ComplexProtoBuf.Car.Holder.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private Builder(BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
            getAddressFieldBuilder();
          }
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          firstName_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          lastName_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          if (addressBuilder_ == null) {
            address_ = com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address.getDefaultInstance();
          } else {
            addressBuilder_.clear();
          }
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.whg.protobuf.ComplexProtoBuf.Car.Holder.getDescriptor();
        }
        
        public com.whg.protobuf.ComplexProtoBuf.Car.Holder getDefaultInstanceForType() {
          return com.whg.protobuf.ComplexProtoBuf.Car.Holder.getDefaultInstance();
        }
        
        public com.whg.protobuf.ComplexProtoBuf.Car.Holder build() {
          com.whg.protobuf.ComplexProtoBuf.Car.Holder result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private com.whg.protobuf.ComplexProtoBuf.Car.Holder buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          com.whg.protobuf.ComplexProtoBuf.Car.Holder result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public com.whg.protobuf.ComplexProtoBuf.Car.Holder buildPartial() {
          com.whg.protobuf.ComplexProtoBuf.Car.Holder result = new com.whg.protobuf.ComplexProtoBuf.Car.Holder(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.firstName_ = firstName_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.lastName_ = lastName_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          if (addressBuilder_ == null) {
            result.address_ = address_;
          } else {
            result.address_ = addressBuilder_.build();
          }
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.whg.protobuf.ComplexProtoBuf.Car.Holder) {
            return mergeFrom((com.whg.protobuf.ComplexProtoBuf.Car.Holder)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(com.whg.protobuf.ComplexProtoBuf.Car.Holder other) {
          if (other == com.whg.protobuf.ComplexProtoBuf.Car.Holder.getDefaultInstance()) return this;
          if (other.hasFirstName()) {
            setFirstName(other.getFirstName());
          }
          if (other.hasLastName()) {
            setLastName(other.getLastName());
          }
          if (other.hasAddress()) {
            mergeAddress(other.getAddress());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public final boolean isInitialized() {
          if (!hasLastName()) {
            
            return false;
          }
          if (hasAddress()) {
            if (!getAddress().isInitialized()) {
              
              return false;
            }
          }
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                firstName_ = input.readBytes();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                lastName_ = input.readBytes();
                break;
              }
              case 26: {
                com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address.Builder subBuilder = com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address.newBuilder();
                if (hasAddress()) {
                  subBuilder.mergeFrom(getAddress());
                }
                input.readMessage(subBuilder, extensionRegistry);
                setAddress(subBuilder.buildPartial());
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // optional string first_name = 1;
        private Object firstName_ = "";
        public boolean hasFirstName() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public String getFirstName() {
          Object ref = firstName_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
            firstName_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        public Builder setFirstName(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          firstName_ = value;
          onChanged();
          return this;
        }
        public Builder clearFirstName() {
          bitField0_ = (bitField0_ & ~0x00000001);
          firstName_ = getDefaultInstance().getFirstName();
          onChanged();
          return this;
        }
        void setFirstName(com.google.protobuf.ByteString value) {
          bitField0_ |= 0x00000001;
          firstName_ = value;
          onChanged();
        }
        
        // required string last_name = 2;
        private Object lastName_ = "";
        public boolean hasLastName() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        public String getLastName() {
          Object ref = lastName_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
            lastName_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        public Builder setLastName(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          lastName_ = value;
          onChanged();
          return this;
        }
        public Builder clearLastName() {
          bitField0_ = (bitField0_ & ~0x00000002);
          lastName_ = getDefaultInstance().getLastName();
          onChanged();
          return this;
        }
        void setLastName(com.google.protobuf.ByteString value) {
          bitField0_ |= 0x00000002;
          lastName_ = value;
          onChanged();
        }
        
        // optional .Game.Cars.Car.Vendor.Address address = 3;
        private com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address address_ = com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address.getDefaultInstance();
        private com.google.protobuf.SingleFieldBuilder<
            com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address, com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address.Builder, com.whg.protobuf.ComplexProtoBuf.Car.Vendor.AddressOrBuilder> addressBuilder_;
        public boolean hasAddress() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        public com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address getAddress() {
          if (addressBuilder_ == null) {
            return address_;
          } else {
            return addressBuilder_.getMessage();
          }
        }
        public Builder setAddress(com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address value) {
          if (addressBuilder_ == null) {
            if (value == null) {
              throw new NullPointerException();
            }
            address_ = value;
            onChanged();
          } else {
            addressBuilder_.setMessage(value);
          }
          bitField0_ |= 0x00000004;
          return this;
        }
        public Builder setAddress(
            com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address.Builder builderForValue) {
          if (addressBuilder_ == null) {
            address_ = builderForValue.build();
            onChanged();
          } else {
            addressBuilder_.setMessage(builderForValue.build());
          }
          bitField0_ |= 0x00000004;
          return this;
        }
        public Builder mergeAddress(com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address value) {
          if (addressBuilder_ == null) {
            if (((bitField0_ & 0x00000004) == 0x00000004) &&
                address_ != com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address.getDefaultInstance()) {
              address_ =
                com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address.newBuilder(address_).mergeFrom(value).buildPartial();
            } else {
              address_ = value;
            }
            onChanged();
          } else {
            addressBuilder_.mergeFrom(value);
          }
          bitField0_ |= 0x00000004;
          return this;
        }
        public Builder clearAddress() {
          if (addressBuilder_ == null) {
            address_ = com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address.getDefaultInstance();
            onChanged();
          } else {
            addressBuilder_.clear();
          }
          bitField0_ = (bitField0_ & ~0x00000004);
          return this;
        }
        public com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address.Builder getAddressBuilder() {
          bitField0_ |= 0x00000004;
          onChanged();
          return getAddressFieldBuilder().getBuilder();
        }
        public com.whg.protobuf.ComplexProtoBuf.Car.Vendor.AddressOrBuilder getAddressOrBuilder() {
          if (addressBuilder_ != null) {
            return addressBuilder_.getMessageOrBuilder();
          } else {
            return address_;
          }
        }
        private com.google.protobuf.SingleFieldBuilder<
            com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address, com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address.Builder, com.whg.protobuf.ComplexProtoBuf.Car.Vendor.AddressOrBuilder> 
            getAddressFieldBuilder() {
          if (addressBuilder_ == null) {
            addressBuilder_ = new com.google.protobuf.SingleFieldBuilder<
                com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address, com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address.Builder, com.whg.protobuf.ComplexProtoBuf.Car.Vendor.AddressOrBuilder>(
                    address_,
                    getParentForChildren(),
                    isClean());
            address_ = null;
          }
          return addressBuilder_;
        }
        
        // @@protoc_insertion_point(builder_scope:Game.Cars.Car.Holder)
      }
      
      static {
        defaultInstance = new Holder(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:Game.Cars.Car.Holder)
    }
    
    private int bitField0_;
    // required string model = 1;
    public static final int MODEL_FIELD_NUMBER = 1;
    private Object model_;
    public boolean hasModel() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getModel() {
      Object ref = model_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          model_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getModelBytes() {
      Object ref = model_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        model_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required .Game.Cars.Car.Vendor vendor = 2;
    public static final int VENDOR_FIELD_NUMBER = 2;
    private com.whg.protobuf.ComplexProtoBuf.Car.Vendor vendor_;
    public boolean hasVendor() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.whg.protobuf.ComplexProtoBuf.Car.Vendor getVendor() {
      return vendor_;
    }
    public com.whg.protobuf.ComplexProtoBuf.Car.VendorOrBuilder getVendorOrBuilder() {
      return vendor_;
    }
    
    // optional .Game.Cars.Car.Speed speed = 3 [default = FAST];
    public static final int SPEED_FIELD_NUMBER = 3;
    private com.whg.protobuf.ComplexProtoBuf.Car.Speed speed_;
    public boolean hasSpeed() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public com.whg.protobuf.ComplexProtoBuf.Car.Speed getSpeed() {
      return speed_;
    }
    
    private void initFields() {
      model_ = "";
      vendor_ = com.whg.protobuf.ComplexProtoBuf.Car.Vendor.getDefaultInstance();
      speed_ = com.whg.protobuf.ComplexProtoBuf.Car.Speed.FAST;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasModel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVendor()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getVendor().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getModelBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, vendor_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, speed_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getModelBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, vendor_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, speed_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.whg.protobuf.ComplexProtoBuf.Car parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.whg.protobuf.ComplexProtoBuf.Car parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.whg.protobuf.ComplexProtoBuf.Car parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.whg.protobuf.ComplexProtoBuf.Car parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.whg.protobuf.ComplexProtoBuf.Car parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.whg.protobuf.ComplexProtoBuf.Car parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.whg.protobuf.ComplexProtoBuf.Car parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.whg.protobuf.ComplexProtoBuf.Car parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.whg.protobuf.ComplexProtoBuf.Car parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.whg.protobuf.ComplexProtoBuf.Car parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.whg.protobuf.ComplexProtoBuf.Car prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.whg.protobuf.ComplexProtoBuf.CarOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.whg.protobuf.ComplexProtoBuf.internal_static_Game_Cars_Car_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.whg.protobuf.ComplexProtoBuf.internal_static_Game_Cars_Car_fieldAccessorTable;
      }
      
      // Construct using com.whg.protobuf.ComplexProtoBuf.Car.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getVendorFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        model_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (vendorBuilder_ == null) {
          vendor_ = com.whg.protobuf.ComplexProtoBuf.Car.Vendor.getDefaultInstance();
        } else {
          vendorBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        speed_ = com.whg.protobuf.ComplexProtoBuf.Car.Speed.FAST;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.whg.protobuf.ComplexProtoBuf.Car.getDescriptor();
      }
      
      public com.whg.protobuf.ComplexProtoBuf.Car getDefaultInstanceForType() {
        return com.whg.protobuf.ComplexProtoBuf.Car.getDefaultInstance();
      }
      
      public com.whg.protobuf.ComplexProtoBuf.Car build() {
        com.whg.protobuf.ComplexProtoBuf.Car result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.whg.protobuf.ComplexProtoBuf.Car buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.whg.protobuf.ComplexProtoBuf.Car result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.whg.protobuf.ComplexProtoBuf.Car buildPartial() {
        com.whg.protobuf.ComplexProtoBuf.Car result = new com.whg.protobuf.ComplexProtoBuf.Car(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.model_ = model_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (vendorBuilder_ == null) {
          result.vendor_ = vendor_;
        } else {
          result.vendor_ = vendorBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.speed_ = speed_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.whg.protobuf.ComplexProtoBuf.Car) {
          return mergeFrom((com.whg.protobuf.ComplexProtoBuf.Car)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.whg.protobuf.ComplexProtoBuf.Car other) {
        if (other == com.whg.protobuf.ComplexProtoBuf.Car.getDefaultInstance()) return this;
        if (other.hasModel()) {
          setModel(other.getModel());
        }
        if (other.hasVendor()) {
          mergeVendor(other.getVendor());
        }
        if (other.hasSpeed()) {
          setSpeed(other.getSpeed());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasModel()) {
          
          return false;
        }
        if (!hasVendor()) {
          
          return false;
        }
        if (!getVendor().isInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              model_ = input.readBytes();
              break;
            }
            case 18: {
              com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Builder subBuilder = com.whg.protobuf.ComplexProtoBuf.Car.Vendor.newBuilder();
              if (hasVendor()) {
                subBuilder.mergeFrom(getVendor());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setVendor(subBuilder.buildPartial());
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              com.whg.protobuf.ComplexProtoBuf.Car.Speed value = com.whg.protobuf.ComplexProtoBuf.Car.Speed.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                speed_ = value;
              }
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string model = 1;
      private Object model_ = "";
      public boolean hasModel() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getModel() {
        Object ref = model_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          model_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setModel(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        model_ = value;
        onChanged();
        return this;
      }
      public Builder clearModel() {
        bitField0_ = (bitField0_ & ~0x00000001);
        model_ = getDefaultInstance().getModel();
        onChanged();
        return this;
      }
      void setModel(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        model_ = value;
        onChanged();
      }
      
      // required .Game.Cars.Car.Vendor vendor = 2;
      private com.whg.protobuf.ComplexProtoBuf.Car.Vendor vendor_ = com.whg.protobuf.ComplexProtoBuf.Car.Vendor.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.whg.protobuf.ComplexProtoBuf.Car.Vendor, com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Builder, com.whg.protobuf.ComplexProtoBuf.Car.VendorOrBuilder> vendorBuilder_;
      public boolean hasVendor() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.whg.protobuf.ComplexProtoBuf.Car.Vendor getVendor() {
        if (vendorBuilder_ == null) {
          return vendor_;
        } else {
          return vendorBuilder_.getMessage();
        }
      }
      public Builder setVendor(com.whg.protobuf.ComplexProtoBuf.Car.Vendor value) {
        if (vendorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          vendor_ = value;
          onChanged();
        } else {
          vendorBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setVendor(
          com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Builder builderForValue) {
        if (vendorBuilder_ == null) {
          vendor_ = builderForValue.build();
          onChanged();
        } else {
          vendorBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergeVendor(com.whg.protobuf.ComplexProtoBuf.Car.Vendor value) {
        if (vendorBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              vendor_ != com.whg.protobuf.ComplexProtoBuf.Car.Vendor.getDefaultInstance()) {
            vendor_ =
              com.whg.protobuf.ComplexProtoBuf.Car.Vendor.newBuilder(vendor_).mergeFrom(value).buildPartial();
          } else {
            vendor_ = value;
          }
          onChanged();
        } else {
          vendorBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearVendor() {
        if (vendorBuilder_ == null) {
          vendor_ = com.whg.protobuf.ComplexProtoBuf.Car.Vendor.getDefaultInstance();
          onChanged();
        } else {
          vendorBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      public com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Builder getVendorBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getVendorFieldBuilder().getBuilder();
      }
      public com.whg.protobuf.ComplexProtoBuf.Car.VendorOrBuilder getVendorOrBuilder() {
        if (vendorBuilder_ != null) {
          return vendorBuilder_.getMessageOrBuilder();
        } else {
          return vendor_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.whg.protobuf.ComplexProtoBuf.Car.Vendor, com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Builder, com.whg.protobuf.ComplexProtoBuf.Car.VendorOrBuilder> 
          getVendorFieldBuilder() {
        if (vendorBuilder_ == null) {
          vendorBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.whg.protobuf.ComplexProtoBuf.Car.Vendor, com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Builder, com.whg.protobuf.ComplexProtoBuf.Car.VendorOrBuilder>(
                  vendor_,
                  getParentForChildren(),
                  isClean());
          vendor_ = null;
        }
        return vendorBuilder_;
      }
      
      // optional .Game.Cars.Car.Speed speed = 3 [default = FAST];
      private com.whg.protobuf.ComplexProtoBuf.Car.Speed speed_ = com.whg.protobuf.ComplexProtoBuf.Car.Speed.FAST;
      public boolean hasSpeed() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public com.whg.protobuf.ComplexProtoBuf.Car.Speed getSpeed() {
        return speed_;
      }
      public Builder setSpeed(com.whg.protobuf.ComplexProtoBuf.Car.Speed value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        speed_ = value;
        onChanged();
        return this;
      }
      public Builder clearSpeed() {
        bitField0_ = (bitField0_ & ~0x00000004);
        speed_ = com.whg.protobuf.ComplexProtoBuf.Car.Speed.FAST;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:Game.Cars.Car)
    }
    
    static {
      defaultInstance = new Car(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Game.Cars.Car)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Game_Cars_Car_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Game_Cars_Car_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Game_Cars_Car_Vendor_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Game_Cars_Car_Vendor_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Game_Cars_Car_Vendor_Address_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Game_Cars_Car_Vendor_Address_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Game_Cars_Car_Holder_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Game_Cars_Car_Holder_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rComplex.proto\022\tGame.Cars\"\315\002\n\003Car\022\r\n\005mo" +
      "del\030\001 \002(\t\022%\n\006vendor\030\002 \002(\0132\025.Game.Cars.Ca" +
      "r.Vendor\022)\n\005speed\030\003 \001(\0162\024.Game.Cars.Car." +
      "Speed:\004FAST\032b\n\006Vendor\022\014\n\004name\030\001 \002(\t\022.\n\007a" +
      "ddress\030\002 \001(\0132\035.Game.Cars.Car.Vendor.Addr" +
      "ess\032\032\n\007Address\022\017\n\007country\030\001 \002(\t\032_\n\006Holde" +
      "r\022\022\n\nfirst_name\030\001 \001(\t\022\021\n\tlast_name\030\002 \002(\t" +
      "\022.\n\007address\030\003 \001(\0132\035.Game.Cars.Car.Vendor" +
      ".Address\" \n\005Speed\022\010\n\004FAST\020\001\022\r\n\tSUPERFAST" +
      "\020\002B#\n\020com.whg.protobufB\017ComplexProtoBuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Game_Cars_Car_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Game_Cars_Car_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Game_Cars_Car_descriptor,
              new java.lang.String[] { "Model", "Vendor", "Speed", },
              com.whg.protobuf.ComplexProtoBuf.Car.class,
              com.whg.protobuf.ComplexProtoBuf.Car.Builder.class);
          internal_static_Game_Cars_Car_Vendor_descriptor =
            internal_static_Game_Cars_Car_descriptor.getNestedTypes().get(0);
          internal_static_Game_Cars_Car_Vendor_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Game_Cars_Car_Vendor_descriptor,
              new java.lang.String[] { "Name", "Address", },
              com.whg.protobuf.ComplexProtoBuf.Car.Vendor.class,
              com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Builder.class);
          internal_static_Game_Cars_Car_Vendor_Address_descriptor =
            internal_static_Game_Cars_Car_Vendor_descriptor.getNestedTypes().get(0);
          internal_static_Game_Cars_Car_Vendor_Address_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Game_Cars_Car_Vendor_Address_descriptor,
              new java.lang.String[] { "Country", },
              com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address.class,
              com.whg.protobuf.ComplexProtoBuf.Car.Vendor.Address.Builder.class);
          internal_static_Game_Cars_Car_Holder_descriptor =
            internal_static_Game_Cars_Car_descriptor.getNestedTypes().get(1);
          internal_static_Game_Cars_Car_Holder_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Game_Cars_Car_Holder_descriptor,
              new java.lang.String[] { "FirstName", "LastName", "Address", },
              com.whg.protobuf.ComplexProtoBuf.Car.Holder.class,
              com.whg.protobuf.ComplexProtoBuf.Car.Holder.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
